### ISSUE TITLE
Hintergrundfarben Titelbilder

### ISSUE THREAD

**Issue by katjavolk** [katjavolk/portfolio#11]
Für jedes Projekt eine Hintergrundfarbe zum erweitern des Titelbildes festlegen

**Comment by katjavolk** [comment]
Wizard: #135F84
silent songs: #000000
geometry+: #ffffff
die geschichte des Horrors: #CE2E37
schweinchen: #FFC9E0
Opti:pessi: #27272C
wabi Phone: #F7BC15
Tinkefestival: #2AE1FF
pretzelprinter: #000000

**Comment by katjavolk** [comment]
Farben einfügen

**Comment by marc-fischer** [comment]
@katjavolk Bitte testen ob die Farben richtig sind
